apiVersion: v1
kind: Service

metadata:
  name: customer-api-service
  namespace: ecommerce
  labels:
    app: customer-api-service
    env: non-prod

spec:
  selector:
    app: customer-api
    env: non-prod
  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080



