apiVersion: v1
kind: Service

metadata:
  name: inventory-api-service
  namespace: ecommerce
  labels:
    app: inventory-api-service
    env: non-prod

spec:
  type: ClusterIP
  selector:
    app: inventory-api
    env: non-prod
  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080



