name: Build Docker Images

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      service:
        description: Service to Build
        required: true
        default: all
        type: choice
        options:
          - all
          - customer-api
          - inventory-api
          - payment-api
          - notification-api
          - order-api
          - ecommerce-ui

      version:
        description: Docker Image Version
        required: true
        default: "1.0.0"

      push_latest:
        description: Push latest tag
        required: true
        default: true
        type: boolean

env:
  REGISTRY: ${{ vars.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}

jobs:

  docker:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:

        include:

          - service: customer-api
            image: customer-api
            dockerfile: src/Customer.Api/Dockerfile

          - service: inventory-api
            image: inventory-api
            dockerfile: src/Inventory.Api/Dockerfile

          - service: payment-api
            image: payment-api
            dockerfile: src/Payment.Api/Dockerfile

          - service: notification-api
            image: notification-api
            dockerfile: src/Notification.Api/Dockerfile

          - service: order-api
            image: order-api
            dockerfile: src/Order.Api/Dockerfile

          - service: ecommerce-ui
            image: ecommerce-ui
            dockerfile: frontend/Dockerfile

    if: |
      github.event_name == 'push' ||
      github.event.inputs.service == 'all' ||
      github.event.inputs.service == matrix.service

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore Ecommerce.sln

      - name: Build
        run: dotnet build Ecommerce.sln --configuration Release --no-restore

      - name: Docker Login
        uses: ./.github/actions/docker-login

      - name: Docker Build
        uses: ./.github/actions/docker-build

        with:

          image-name: ${{ matrix.image }}

          dockerfile: ${{ matrix.dockerfile }}

          version: ${{ github.event_name == 'push' && '1.0.0' || github.event.inputs.version }}

          push-latest: ${{ github.event_name == 'push' && 'true' || github.event.inputs.push_latest }}